version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - go
  go:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - "8081:8081"